//Public
//Alert
export const SET_ALERT        = "SET_ALERT";
export const REMOVE_ALERT     = "REMOVE_ALERT";
//AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL    = "REGISTER_FAIL";
export const USER_LOADED      = "USER_LOADED";
export const AUTH_ERROR       = "AUTH_ERROR";
export const LOGIN_SUCCESS    = "LOGIN_SUCCESS";
export const LOGIN_FAIL       = "LOGIN_FAIL";
export const LOGOUT           = "LOGOUT";
//Products
export const GET_PRODUCTS     = "GET_PRODUCTS";
export const GET_PRODUCT      = "GET_PRODUCT";
export const LOAD_ERROR       = "LOAD_ERROR";
//Reviews
export const GET_REVIEWS      = "GET_REVIEWS";
export const ADD_REVIEW       = "ADD_REVIEW";
export const LOAD_REVIEWS     = "LOAD_REVIEWS";
export const REVIEW_ERROR     = "REVIEW_ERROR";
// Orders
export const ADD_ORDER                 = "ADD_ORDER";
export const ORDER_ERROR               = "ORDER_ERROR";
export const POSTING_ORDER             = "POSTING_ORDER";
export const RESET_ORDER               = "RESET_ORDER";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_ERROR = "GET_SINGLE_ORDER_ERROR";
export const GET_SINGLE_ORDER_LOADING = "GET_SINGLE_ORDER_LOADING";

//Profiles
export const GET_PROFILE               = "GET_PROFILE";
export const UPDATE_PROFILE            = "UPDATE_PROFILE";
//ADMIN
export const REMOVE_PRODUCT_SUCCESS     = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_ERROR       = "REMOVE_PRODUCT_ERROR";
export const REMOVE_PRODUCT_LOADING     = "REMOVE_PRODUCT_LOADING";
export const ADD_PRODUCT_SUCCESS        = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR          = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_LOADING        = "ADD_PRODUCT_LOADING";
export const UPDATE_PRODUCT_SUCCESS     = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_LOADING     = "UPDATE_PRODUCT_LOADING";
export const UPDATE_PRODUCT_ERROR       = "UPDATE_PRODUCT_ERROR";

export const RESET_PRODUCT_ADD_UPDATE = "RESET_PRODUCT_ADD_UPDATE";

//ADMIN REVIEWS
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS";
export const GET_ALL_REVIEWS_ERROR   = "GET_ALL_REVIEWS_ERROR";
export const REMOVE_REVIEW_LOADING   = "REMOVE_REVIEW_LOADING";
export const REMOVE_REVIEW_SUCCESS   = "REMOVE_REVIEW_SUCCESS";
export const REMOVE_REVIEW_ERROR     = "REMOVE_REVIEW_ERROR";

 
//ADMIN ORDER
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";
export const GET_ORDER_LOADING = "GET_ORDER_LOADING";


export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_LOADING = "UPDATE_ORDER_LOADING";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

export const REMOVE_ORDER_SUCCESS = "REMOVE_ORDER_SUCCESS";
export const REMOVE_ORDER_LOADING = "REMOVE_ORDER_LOADING";
export const REMOVE_ORDER_ERROR = "REMOVE_ORDER_ERROR";

export const RESET_ORDER_UPDATE = "RESET_ORDER_UPDATE";
